version: 2

project_name: stack-analyzer

before:
  hooks:
    - go mod tidy

builds:
  - id: stack-analyzer
    main: ./cmd/scanner
    binary: stack-analyzer
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/petrarca/tech-stack-analyzer/internal/version.Version={{.Version}}
      - -X github.com/petrarca/tech-stack-analyzer/internal/version.Commit={{.Commit}}
      - -X github.com/petrarca/tech-stack-analyzer/internal/version.Date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: petrarca
    name: tech-stack-analyzer
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"
